# Generated by Django 4.0.2 on 2022-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='nombre_producto')),
                ('cantidad_producto', models.IntegerField(verbose_name='cantidad_producto')),
                ('precio_producto', models.FloatField(verbose_name='precio_producto')),
                ('descripcion_producto', models.CharField(max_length=200, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('id_usuario', models.CharField(max_length=50, verbose_name='apellido')),
                ('contraseña', models.CharField(max_length=50, verbose_name='contraseña')),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
