# Generated by Django 4.0.3 on 2022-04-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0002_pedido_producto_usuario_delete_persona'),
        ('AppRegistro', '0002_usuario_delete_persona'),
    ]

    operations = [
    ]
